name: build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu
    strategy:
      matrix:
        python-version: ["2.x", "3.x"]
        click-version: [
          "5.0",
          "5.1",
          "6.0",
          "8.0.0"
        ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install click==${{ matrix.click-version }}
          python setup.py install
      - name: Verify click version
        run: pip freeze click
      - name: Run tests
        run: python -m unittest discover -v
